#pragma once
#include "Label.h"
#include "Register.h"
#include <iostream>
#include <vector>
namespace Loonguage {
	class Code
	{
	public:
		//all label that points at this code
		std::vector<Label> labelAttached;
		enum CodeType {
			AND,
			ANDI,
			OR,
			ORI,
			XOR,
			XORI,
			NOT,
			ADD,
			ADDI,
			SUB,
			MUL,
			DIV,
			SLT,
			B,
			BEQ,
			JR,
			JAL,
			LB,
			LBU,
			LH,
			LHU,
			LW,
			SB,
			SH,
			SW,
			NOP,
			MOVZ,
			MFHI,
			MFLO,
			MTHI,
			MTLO,
			HLT,
			STDIN,
			STDOUT
		};
		CodeType codeType;
		Register::Registers rs;
		Register::Registers rt;
		Register::Registers rd;
		//label as its parameter
		Label label;
		int immediate;
        Code(std::string, bool&);
		Code(CodeType c);
		Code(CodeType c, Label);
		Code(CodeType c, Register::Registers, Register::Registers, Label);
		Code(CodeType c, Register::Registers);
		Code(CodeType c, Register::Registers, Register::Registers);
		Code(CodeType c, Register::Registers, Register::Registers, int);
		Code(CodeType c, Register::Registers, Register::Registers, Register::Registers);
		void dump(std::ostream&) const;
		void addLabel(Label);
		//is generated by string, and position of string has to be calculated after code generation
		bool strPositionToBeAdded = false;
	};

}
